language: generic
before_install:
- mkdir -p ~/artefacts/
jobs:
  include:
  - stage: setup files
    env:
        - ARTIFACTS_BUCKET=travis-artefacts-bilal
    script: 
      - echo one | tee > ~/artefacts/artefact.txt
      - cat ~/artefacts/artefact.txt
#  - stage: use shared files
#    script:
#    - echo "s"
addons:
  artifacts:
    working_dir: ~/artefacts
    paths:
        - ~/artefacts/artefact.txt
    s3_region: us-east-1
env:
  global:
  - secure: kD8PD7ZaPMlZRwC6Ra7DZHzymgTZPcYO1rLJAVid6GydzobO4FALbsd/ThoGatWUMirSDXeScpVRtwx6w0Ce7x+N5xfjTi2AV5XPNxnhraZK6ZbEiy5br5wFz+BVYQ2MbFQrMNKTFfWNjVsnXiGazj0b0sMyqsvFNkQqCH0L7/cWsp6oSkuf49dFU8H5AnUFPQYuf3zm9TkDlcFabOrWbQALuAqV0zz47osMMWcsRrVvgwfnsvbcePHh0LvJCoFSCGzQA6RvMFjJJI7FpaPbhcouV4ltAmzY9xSM+wCe9jFIJFyiHCb5MxXR9QpupcOpXXLKD9uQ5pEGWMHSJSeH7G14liLzU7C3of3OfYLZKu6RGu4Jk3Y3sjiRlfiPiMJ8ejQp1IimCMSeYZCMS4RutnzwXeZFo/Cp8sNMR/Rfrlgdg/7CKusUmwp0FcJHuqyCWsPOlZf8e6aqR/y8wb8Vcuey+1Ca0rIP8NwhKYKl6FfQiLStQDfi43yICa58YJ5jte/ZANtouzBix7tEFS4sXDBPHQBUWyROHS+2OpW4A7zhcwFrexZB5z+s0ByRMI5mbAyajk9/WX8qbsw+Z3O4j4FGbPlUt/9DtS3lU1DLCk8cAiYcnZ2ZTSHK6umDUtyBpEWsHWiQpVvVuoT8A1nVVTjswePQQ91Woq8u4YcGB5k=
  - secure: LqNcTI/NBSmrG9mUv/H7ej8jzTVYSZmskcbD03VyeCJI7vgEv7LanbCmnHDVTDyLkPS3/Vo45Zx8YpwZrsVOOaYEvvVs7R4dQfivgzadEZzt6ozhzT0MEOXU7SAnnv1rX7yry1egz3EXaNu8QDhL35pyaab6UpdtiG5ZcqOyAVLqAUO8Y17XQzawbygMJglHSvCQoLuEl50hFqqEyhBMQL6Rz/leazMe/Yi1ygSJ/GNzzOmg1snrw2llwdT6/aGMTyLUUhmUkf7YmqwNl4UHcJNa70QIMT+cH6zl9kTa9uabLcnKE9XM8jM8pPRHy+Ejs8HNT/amZ1+wxSbwLYxnz/I1NMDF14op0u/JhYNh9EIWZ7AhEqQVlAkuCcogtvemiqkQ55p2415grHtQlM0IPgJ2G0QhyaPzDVgLq75Cjv334gi7NUe8SD905zRbYHT2WzjD5Kdv3idI1wUAg9s0ZLeNL3nuZU6ET9UHf8Bs/85zFaV9+9vtHk5PJ7/qLH66d/2juplyO0MZeTfJgzJWw2oo63rj9aeDlXnNOgfyBknupi8lTxHVqYNKtZjFrMjwjzAC+48f4Kg3IVQ04vC/uujbQjdwCtophOGu5aXfrCm6f3342HsvRqWHwsvFmxMddSye9aNRBVhFsH7PH28WUNgQN4AoKcFglBUCo4kuj+I=