language: generic
before_install:
  - pip install --user awscli #install aws cli
  - mkdir -p ~/artefacts/$TRAVIS_BUILD_NUMBER #create directory for storing artefacts
  # sync s3 before every stage
  - aws s3 sync s3://travis-artefacts-bilal/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER/artefacts

jobs:
  include:
  - stage: setup files
    script: 
      - echo one | tee > ~/artefacts/$TRAVIS_BUILD_NUMBER/data.txt
      - cat ~/artefacts/$TRAVIS_BUILD_NUMBER/data.txt 
    # upload artefacts ofter success of job
    after_success: aws s3 sync ~/artefacts/$TRAVIS_BUILD_NUMBER s3://travis-artefacts-bilal/$TRAVIS_BUILD_NUMBER
  - stage: use shared files
    script:
      - cat ~/artefacts/$TRAVIS_BUILD_NUMBER/data.txt

env:
  global:
  # include $HOME/.local/bin for `aws`
  - PATH=$HOME/.local/bin:$PATH
  - secure: xQngq/0LhXjGJdph8FY0+DyW9HUjiit8EIY6V3ee803tfdsHdCyOwrW/DiJmm/hNsG3f4UxagfTN9wqDVF6hkCtzv13do0zntPQjJXPqhp+Y38qr4GGwAxzJTlVAUhP69WXR1CoIAA/7MgjDcdwzaw0MFSLLJ0ndWeQdj/A9qZD9+JFCkpNQIaMddKSZ03bBg++2EB87CtJ7JT1w2ThM+tT2sQHkXkZ+Ho1PWRlqQ90/0MMRwRrZa5pmDBmeWx9B779KOcP89Fk272bNfuc8dMQziAMwpfZ03grw6PTETqJSicNyppz2shQNzfZZPvWwky89TbO90OTVJlXO4JNxyeibTRA1ASnam/M4Y2WRml8FHsC5mtB0bl4W/Unt6Cp443sRF2mmP0t/L8JBzNpatBU5HkDdeicTon+mp/bWZDsrFXcwgDLMfukecgn7IiGWMWZbonYkBVRTVAQGjpsMIox2CRjb4tQka5N99mnDWLbcULgW4X63d0BAuEkvFb1gPQLkyc1JSlMn6gHhjUkjjOvgpk3beK5kdh/i2fZXu9AEL3hbnrm3P40mJL4qchUEkDjqX0mby3k+jwwOcHvx8GKgkGjSSZAnh1REd1VGG3I8D5xoIv3gU7qYyszJl/2dCQlVGZi3XHYj5TQT/v5QQlS/Zyr3eAMaS8WYUcvvQMw=
  - secure: xzyTo9p8VprxYJONdPDSluvkc0O5VANb11i9ebQlj9EHIgmuZfHty4pHuwv7rp2MEucHCSBlf5RZDXssgwFr8Y0eetmWKfRJnPfM1zPe6vL6XKOJxqySRDm5uGlht+z6pSkNjIKbGQxxl9MnAtOJrIB84uN1oByMthjvY+Mt5IRW3MvtWOB9q+rPMHwlytLLfdZV1H015x3wZsg8/Djcc4n52B+rBUKyk+dJT86edK8RKg41e5M5XKcWDE+QQw5dcHMWH4XADQA/z3pj1I8O/b5TFvezQyGITESmbMGiirlKg2PYWv7C7ilEuultPWhg9t1Agw/vHdD5iLemNJ27PcjJdn2SQDuAIjXc7Pj9JjML+q84goqNhpCVf1JFBnPsmy1IMehFwIcRSDx0yaauDR/5fMHXwmb4SJXR4LB8PpIyo4JCPqRHNmFJgspoehzuNI/gkIkfUySo7h/3bg4Id0NXO8f0wUbz5JS7PkBPZhOZE9ItWD3WZ956EgS0MKqpdN54H8Xs3y1X0CmxykBH1lsNMwDi733XVyBJktNKQ+YPUFLpvzCsscBjV6ETHrNS2RrPx/qAlDvNeagySXQY+GrqcVM74+RYqNOeOnQJawRXifRU/2S6n3lwelNdCQwAqYmQJRLq83WlDJMiWuYEW+ShJC+lijo2zQc7uTE0dY0=
